create table if not exists topics (
  id serial primary key,
  title text not null,
  meta jsonb not null default '{}'
);

insert into topics (title, meta) values
('Your most memorable trip', '{"help_words":[{"word":"Memorable","pronunciation":"[ˈmem(ə)rəb(ə)l]","tags":["special","worth remembering"]},{"word":"Scenery","pronunciation":"[ˈsiːnərɪ]","tags":["natural view","landscape"]},{"word":"Itinerary","pronunciation":"[aɪˈtɪnərərɪ]","tags":["travel plan","route"]},{"word":"Souvenir","pronunciation":"[ˌsuːvəˈnɪə]","tags":["keepsake","memento"]},{"word":"Jet-lagged","pronunciation":"[ˈdʒetlæɡd]","tags":["tired from travel","time zones"]}]}'),
('A skill you wish you had learned earlier', '{"help_words":[{"word":"Proficiency","pronunciation":"[prəˈfɪʃ(ə)nsɪ]","tags":["skill level","expertise"]},{"word":"Dedication","pronunciation":"[ˌdedɪˈkeɪʃ(ə)n]","tags":["commitment","effort"]},{"word":"Hindsight","pronunciation":"[ˈhaɪndsaɪt]","tags":["looking back","reflection"]},{"word":"Perseverance","pronunciation":"[ˌpɜːsɪˈvɪərəns]","tags":["persistence","keep going"]},{"word":"Trial and error","pronunciation":"[ˈtraɪəl ænd ˈerə]","tags":["learning method","experimenting"]}]}'),
('The best advice you have ever received', '{"help_words":[{"word":"Wisdom","pronunciation":"[ˈwɪzdəm]","tags":["good judgement","knowledge"]},{"word":"Mentor","pronunciation":"[ˈmentɔː]","tags":["guide","advisor"]},{"word":"Perspective","pronunciation":"[pəˈspektɪv]","tags":["point of view","outlook"]},{"word":"Turning point","pronunciation":"[ˈtɜːnɪŋ pɔɪnt]","tags":["life change","key moment"]},{"word":"Grateful","pronunciation":"[ˈɡreɪtf(ə)l]","tags":["thankful","appreciative"]}]}'),
('What would you do with a free month off?', '{"help_words":[{"word":"Spontaneous","pronunciation":"[spɒnˈteɪnɪəs]","tags":["unplanned","impulsive"]},{"word":"Recharge","pronunciation":"[ˌriːˈtʃɑːdʒ]","tags":["rest","regain energy"]},{"word":"Bucket list","pronunciation":"[ˈbʌkɪt lɪst]","tags":["life goals","things to do"]},{"word":"Venture","pronunciation":"[ˈventʃə]","tags":["risky journey","new experience"]},{"word":"Unwind","pronunciation":"[ˌʌnˈwaɪnd]","tags":["relax","de-stress"]}]}'),
('A movie or book that changed your view', '{"help_words":[{"word":"Profound","pronunciation":"[prəˈfaʊnd]","tags":["deep","meaningful"]},{"word":"Protagonist","pronunciation":"[prəˈtæɡənɪst]","tags":["main character","hero"]},{"word":"Thought-provoking","pronunciation":"[ˈθɔːt prəˌvəʊkɪŋ]","tags":["makes you think","stimulating"]},{"word":"Narrative","pronunciation":"[ˈnærətɪv]","tags":["story","plot"]},{"word":"Eye-opening","pronunciation":"[ˈaɪ ˌəʊp(ə)nɪŋ]","tags":["surprising","enlightening"]}]}'),
('Your biggest challenge this year', '{"help_words":[{"word":"Obstacle","pronunciation":"[ˈɒbstək(ə)l]","tags":["barrier","difficulty"]},{"word":"Resilience","pronunciation":"[rɪˈzɪlɪəns]","tags":["bounce back","toughness"]},{"word":"Overwhelmed","pronunciation":"[ˌəʊvəˈwelmd]","tags":["too much","swamped"]},{"word":"Cope","pronunciation":"[kəʊp]","tags":["deal with","manage"]},{"word":"Milestone","pronunciation":"[ˈmaɪlstəʊn]","tags":["achievement","key point"]}]}'),
('Your dream job and why', '{"help_words":[{"word":"Passion","pronunciation":"[ˈpæʃ(ə)n]","tags":["strong interest","drive"]},{"word":"Fulfilling","pronunciation":"[fʊlˈfɪlɪŋ]","tags":["satisfying","rewarding"]},{"word":"Vocation","pronunciation":"[vəˈkeɪʃ(ə)n]","tags":["calling","life purpose"]},{"word":"Ambitious","pronunciation":"[æmˈbɪʃəs]","tags":["goal-driven","determined"]},{"word":"Work-life balance","pronunciation":"[ˈwɜːk laɪf ˈbæləns]","tags":["time management","priorities"]}]}'),
('A cultural difference that surprised you', '{"help_words":[{"word":"Custom","pronunciation":"[ˈkʌstəm]","tags":["tradition","habit"]},{"word":"Etiquette","pronunciation":"[ˈetɪket]","tags":["social rules","manners"]},{"word":"Stereotype","pronunciation":"[ˈsterɪətaɪp]","tags":["assumption","generalisation"]},{"word":"Open-minded","pronunciation":"[ˌəʊp(ə)n ˈmaɪndɪd]","tags":["accepting","tolerant"]},{"word":"Fascinating","pronunciation":"[ˈfæsɪneɪtɪŋ]","tags":["interesting","captivating"]}]}'),
('Technology: blessing or curse?', '{"help_words":[{"word":"Distraction","pronunciation":"[dɪˈstrækʃ(ə)n]","tags":["loss of focus","interruption"]},{"word":"Innovation","pronunciation":"[ˌɪnəˈveɪʃ(ə)n]","tags":["new idea","advancement"]},{"word":"Dependency","pronunciation":"[dɪˈpendənsɪ]","tags":["reliance","addiction"]},{"word":"Productivity","pronunciation":"[ˌprɒdʌkˈtɪvɪtɪ]","tags":["efficiency","output"]},{"word":"Double-edged sword","pronunciation":"[ˌdʌb(ə)l edʒd ˈsɔːd]","tags":["has pros and cons","two sides"]}]}'),
('If you could live anywhere, where and why?', '{"help_words":[{"word":"Climate","pronunciation":"[ˈklaɪmɪt]","tags":["weather","environment"]},{"word":"Cost of living","pronunciation":"[kɒst əv ˈlɪvɪŋ]","tags":["expenses","affordability"]},{"word":"Community","pronunciation":"[kəˈmjuːnɪtɪ]","tags":["neighbours","social life"]},{"word":"Vibe","pronunciation":"[vaɪb]","tags":["atmosphere","feel"]},{"word":"Trade-off","pronunciation":"[ˈtreɪd ɒf]","tags":["compromise","give and take"]}]}');
